### ISSUE TITLE
ch1 - time - issue in strange version of pom.xml

### ISSUE THREAD

**Issue by thibautrety** [johanvos/quantumjava#13]
Hello, 

If I run "ch1 - time"  example, I get an error stating that 0.1.2-SNAPSHOT version of org.redfx.strange cannot be found.
In corresponding pom.xml, I suggest to replace 0.1.2-SNAPSHOT by 0.1.3.

Regards

**Comment by johanvos** [comment]
Correct, thanks for reporting this! I'll fix this.
