### ISSUE TITLE
quantumjava/ch11/jshell/checkperiod

### ISSUE THREAD

**Issue by brycelin** [johanvos/quantumjava#14]
Question: shouldn't it be "a" instead of "p" inside the loop for a^p?

for (int i = 0; i < p; i++) {
    u = (u * a) % N;
}
vs
for (int i = 0; i < p; i++) {
    u = (u * p) % N;
}

**Comment by johanvos** [comment]
Yes you are right. Great catch, thanks!
I'll fix it.
