### ISSUE TITLE
ch5 - cnot example - wrong final qubit states in visual output?

### ISSUE THREAD

**Issue by DannyHindson** [johanvos/quantumjava#20]
When I run the cnot example I get the following visual output. It appears that the pink boxes showing the final qubit states have all been set to the values in the final plot generated from run11():

![image](https://user-images.githubusercontent.com/56295817/233383584-9d8339fa-f0fa-4b3b-939c-37cdb9c732dc.png)
![image](https://user-images.githubusercontent.com/56295817/233383629-f74f982f-664e-4e1b-87c3-798781abf421.png)

If run the four scenarios individually (eg by commenting out 3 of the 4 calls in main) I get the correct output. Here's what I get from run00() when I run it on its own:

![image](https://user-images.githubusercontent.com/56295817/233382809-d50cea38-26a2-4653-8c02-f64f161afb72.png)

Not sure if I've done something wrong but thought I'd report it in case it's a real problem

**Comment by johanvos** [comment]
@DannyHindson Are you running the sample with maven or gradle?
I notice that the build.gradle file depends on an old version of strangefx (0.0.10) which had a bug. Using 0.1.0 or later should work fine (and that is what the maven pom.xml is using).
I'll fix the build.gradle version -- thanks for detecting this!

**Comment by DannyHindson** [comment]
Yes I was using gradle. I've just made the version change in the commit you pushed yesterday and that's fixed it. The visual output is now correct on the four plots when I run them all together. Thanks!
