### ISSUE TITLE
Toffoli and cNot not correctly represented

### ISSUE THREAD

**Issue by javabean68** [johanvos/quantumjava#29]
Hi,

really nice library and book :)

I have only a question: the not gate and the toffoli one are shown in a strange :) way:
![image](https://github.com/user-attachments/assets/c74978f0-3223-443c-9586-4c5477716589)

![image](https://github.com/user-attachments/assets/d21583ff-9429-41c6-94b9-8ce2fe9527be)

Any hint?
Many thanks in advance
Regards 
Fabio

**Comment by johanvos** [comment]
This is a bug indeed. Thanks for reporting, I'll have a look.

**Comment by johanvos** [comment]
Should be fixed by #30
